#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NZWeatherApp4.Resource", IsApplication=true)]

namespace NZWeatherApp4
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::NZWeatherApp4.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int place_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000b
			public const int AllText = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int City = 2131165200;
			
			// aapt resource value: 0x7f070001
			public const int GetWeatherButton = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int Image = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int ResultsTitle = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int TempText = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int btnGPS = 2131165192;
			
			// aapt resource value: 0x7f07000f
			public const int bullet = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int icon = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout1 = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout2 = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout3 = 2131165187;
			
			// aapt resource value: 0x7f07000d
			public const int message = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int scrollView1 = 2131165194;
			
			// aapt resource value: 0x7f070002
			public const int spCity = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int txtGPS = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int widget = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TempText = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int widget = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int place_prompt = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int widget = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
